### ISSUE TITLE
Currently, the Extension window is too narrow, no information is displayed

### ISSUE THREAD

**Issue by kyotayokoo** [mindsphere/mindsphere-auth-helper#14]
The window is too narrow.
![image](https://github.com/mindsphere/mindsphere-auth-helper/assets/94743164/4d6b3376-7da2-4dbb-bea7-221dc49f916f)

Not sure when this started. Another user and I confirmed the issue.
Chrome:
117.0.5938.152 
118.0.5993.71

**Comment by sn0wcat** [comment]
Thank you for reporting this @kyotayokoo , this was introduced with some chrome rendering issue, there seem to be a lot of extensions which suddenly lost width. 

I will look into this.

**Comment by sn0wcat** [comment]
is fixed with #15 - the chrome store will need a few days for publishing the new version of the extension, if you are in a hurry you can clone the repository and load the extension via "load unpacked" in Chrome extension manager.

**Comment by sn0wcat** [comment]
The extension is now also available in the chrome store.

https://chromewebstore.google.com/detail/mindsphere-authentication/licndiiilobojikmhmmcgdbpmnmdeoee
